export interface PricingPackage { id: string; title: string; category: string; price: string; timeline: string; description: string; features: string[]; image: string; popular?: boolean }

export const pricingPackages: PricingPackage[] = [
  { id: 'katra-police', title: 'Katra Police Station', category: 'Institutional', price: 'View', timeline: 'Katra, Jammu & Kashmir', description: 'A civic project balancing public function, identity and a clear architectural presence.', features: ['Institutional planning', 'Public-use design'], image: '/vastukar/katra-police.jpg', popular: true },
  { id: 'jkssb', title: 'J&K Service Selection Board', category: 'Institutional', price: 'View', timeline: 'Jammu, J&K', description: 'Purpose-led institutional planning developed for efficient movement and daily operations.', features: ['Functional planning', 'Institutional architecture'], image: '/vastukar/jkssb.jpg', popular: true },
  { id: 'chib-gate', title: 'Chib Devsthan Gate', category: 'Cultural', price: 'View', timeline: 'Jammu Region', description: 'A distinctive gateway shaped around arrival, identity and its cultural setting.', features: ['Gateway design', 'Context-led detailing'], image: '/vastukar/chib-gate.jpg' },
  { id: 'kargil-bhawan', title: 'Kargil Bhawan', category: 'Institutional', price: 'View', timeline: 'Jammu & Kashmir', description: 'An institutional environment planned for durability, clarity and long-term use.', features: ['Institutional design', 'Project coordination'], image: '/vastukar/kargil-bhawan.jpg' },
  { id: 'yoga-hall', title: 'Yoga Hall for Ayush Gram', category: 'Wellness', price: 'View', timeline: 'Jammu & Kashmir', description: 'A calm wellness space planned around light, openness and collective practice.', features: ['Wellness architecture', 'Interior planning'], image: '/vastukar/yoga-hall.jpg' },
  { id: 'school-block', title: 'School Building Secondary Block', category: 'Education', price: 'View', timeline: 'Jammu & Kashmir', description: 'An education-focused block designed around learning, circulation and practical use.', features: ['Education planning', 'Institutional architecture'], image: '/vastukar/school-building.jpg' },
]
